[package]
name = "eg-examples"
version = "0.1.0"
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
chrono = "0.4.19"
eg-seven-segment = "0.2.0"
embedded-graphics = "0.8.1"
embedded-graphics-simulator = "0.7.0"
embedded-text = "0.7.2"
tinybmp = "0.6.0"
tinytga = "0.5.0"
